fontyourface.font_style.*:
  type: config_entity
  label: 'Font style config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
